#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = x28_read
SRC = x28_read.c
LOCAL_CFLAGS = -O
LOCAL_LIBES = -lnsl -lsocket -lmos -llog
DIP_LIBS = ${PX25HOME}/lib/libmos.a ${PX25HOME}/lib/liblog.a

include	${PX25HOME}/doc/makefile.std
# DO NOT DELETE THIS LINE -- make depend depends on it.

shell_x28.o: /usr/include/stdio.h /usr/include/errno.h
shell_x28.o: /usr/include/sys/errno.h /usr/include/fcntl.h
shell_x28.o: /usr/include/sys/types.h /usr/include/sys/fcntl.h
shell_x28.o: /usr/include/signal.h /usr/include/sys/signal.h
shell_x28.o: /usr/include/sys/time.h /usr3/px25/include/px25_globals.h
shell_x28.o: /usr3/px25/include/errlog.h
# DEBUG Objects Dependencies

shell_x28.do: /usr/include/stdio.h /usr/include/errno.h
shell_x28.do: /usr/include/sys/errno.h /usr/include/fcntl.h
shell_x28.do: /usr/include/sys/types.h /usr/include/sys/fcntl.h
shell_x28.do: /usr/include/signal.h /usr/include/sys/signal.h
shell_x28.do: /usr/include/sys/time.h /usr3/px25/include/px25_globals.h
shell_x28.do: /usr3/px25/include/errlog.h
