#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = rt_bench
SRC = rt_bench.c
LOCAL_CFLAGS = -g
LOCAL_LIBES = ../librouter/librouter.a
DIP_LIBS =

include	${PX25HOME}/doc/makefile.std
# DO NOT DELETE THIS LINE -- make depend depends on it.

sm_test.o: /usr/include/stdio.h
# DEBUG Objects Dependencies

sm_test.do: /usr/include/stdio.h
