#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = gptest
SRC = gptest.c
LOCAL_CFLAGS = -g -D_POSIX_SOURCE
LOCAL_LIBES = ../liblog.a
DIP_LIBS =

include	${PX25HOME}/doc/makefile.std
# DO NOT DELETE THIS LINE -- make depend depends on it.

gptest.o: /usr/include/stdio.h
# DEBUG Objects Dependencies

gptest.do: /usr/include/stdio.h
