#
# LIB = library name
# SRC = list of source files the library is made of.
# LOCAL_CFLAGS = list of private Compiler flags
# WARNING : if library is a local one, comment the line after install:
# ( Do not install in project lib dir )
#

LIB = libsmreq.a
SRC = cl_data.c sm_create_rt.c sm_best_rt.c sm_list_rt.c sm_incr_rt.c \
sm_free_rt.c sm_delete_rt.c sm_debug.c sm_enddebug.c sm_dump_rt.c sm_load_rt.c \
smp_xdr.c smp_clnt.c
LOCAL_CFLAGS = -g

.SUFFIXES: .uil .uid .do

include	${PX25HOME}/doc/makefile.libstd
# DO NOT DELETE THIS LINE -- make depend depends on it.

cl_data.o: /usr/include/stdio.h /usr/include/rpc/rpc.h
cl_data.o: /usr/include/rpc/types.h /usr/include/sys/types.h
cl_data.o: /usr/include/sys/time.h /usr/include/sys/tiuser.h
cl_data.o: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
cl_data.o: /usr/include/sys/stream.h /usr/include/sys/cred.h
cl_data.o: /usr/include/sys/vnode.h /usr/include/sys/mac.h
cl_data.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
cl_data.o: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
cl_data.o: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
cl_data.o: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
cl_data.o: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
cl_data.o: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
cl_data.o: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
cl_data.o: /usr/include/rpc/svc.h /usr/include/sys/select.h
cl_data.o: /usr/include/rpc/svc_auth.h
sm_create_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_create_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_create_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_create_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_create_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_create_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_create_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_create_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_create_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_create_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_create_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_create_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_create_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_create_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_create_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_create_rt.o: /usr/px25/include/smp.h sm.h
sm_best_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_best_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_best_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_best_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_best_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_best_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_best_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_best_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_best_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_best_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_best_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_best_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_best_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_best_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_best_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_best_rt.o: /usr/px25/include/px25_globals.h /usr/px25/include/smp.h sm.h
sm_best_rt.o: /usr/px25/include/group.h
sm_list_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_list_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_list_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_list_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_list_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_list_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_list_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_list_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_list_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_list_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_list_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_list_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_list_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_list_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_list_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_list_rt.o: /usr/px25/include/smp.h sm.h
sm_incr_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_incr_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_incr_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_incr_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_incr_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_incr_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_incr_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_incr_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_incr_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_incr_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_incr_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_incr_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_incr_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_incr_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_incr_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_incr_rt.o: /usr/px25/include/smp.h sm.h
sm_free_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_free_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_free_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_free_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_free_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_free_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_free_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_free_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_free_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_free_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_free_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_free_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_free_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_free_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_free_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_free_rt.o: /usr/px25/include/smp.h sm.h
sm_delete_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_delete_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_delete_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_delete_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_delete_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_delete_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_delete_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_delete_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_delete_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_delete_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_delete_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_delete_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_delete_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_delete_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_delete_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_delete_rt.o: /usr/px25/include/smp.h sm.h
sm_debug.o: /usr/include/stdio.h /usr/include/stdlib.h /usr/include/rpc/rpc.h
sm_debug.o: /usr/include/rpc/types.h /usr/include/sys/types.h
sm_debug.o: /usr/include/sys/time.h /usr/include/sys/tiuser.h
sm_debug.o: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
sm_debug.o: /usr/include/sys/stream.h /usr/include/sys/cred.h
sm_debug.o: /usr/include/sys/vnode.h /usr/include/sys/mac.h
sm_debug.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
sm_debug.o: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
sm_debug.o: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
sm_debug.o: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
sm_debug.o: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
sm_debug.o: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
sm_debug.o: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
sm_debug.o: /usr/include/rpc/svc.h /usr/include/sys/select.h
sm_debug.o: /usr/include/rpc/svc_auth.h /usr/px25/include/smp.h sm.h
sm_enddebug.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_enddebug.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_enddebug.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_enddebug.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_enddebug.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_enddebug.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_enddebug.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_enddebug.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_enddebug.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_enddebug.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_enddebug.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_enddebug.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_enddebug.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_enddebug.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_enddebug.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_enddebug.o: /usr/px25/include/smp.h sm.h
sm_dump_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_dump_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_dump_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_dump_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_dump_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_dump_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_dump_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_dump_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_dump_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_dump_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_dump_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_dump_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_dump_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_dump_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_dump_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_dump_rt.o: /usr/px25/include/smp.h sm.h
sm_load_rt.o: /usr/include/stdio.h /usr/include/stdlib.h
sm_load_rt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_load_rt.o: /usr/include/sys/types.h /usr/include/sys/time.h
sm_load_rt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
sm_load_rt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
sm_load_rt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
sm_load_rt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
sm_load_rt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
sm_load_rt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
sm_load_rt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
sm_load_rt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
sm_load_rt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
sm_load_rt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
sm_load_rt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
sm_load_rt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
sm_load_rt.o: /usr/px25/include/smp.h sm.h
smp_xdr.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_xdr.o: /usr/include/sys/types.h /usr/include/sys/time.h
smp_xdr.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
smp_xdr.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
smp_xdr.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
smp_xdr.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
smp_xdr.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
smp_xdr.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
smp_xdr.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
smp_xdr.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
smp_xdr.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
smp_xdr.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
smp_xdr.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
smp_xdr.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
smp_xdr.o: /usr/px25/include/smp.h
smp_clnt.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_clnt.o: /usr/include/sys/types.h /usr/include/sys/time.h
smp_clnt.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
smp_clnt.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
smp_clnt.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
smp_clnt.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
smp_clnt.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
smp_clnt.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
smp_clnt.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
smp_clnt.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
smp_clnt.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
smp_clnt.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
smp_clnt.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
smp_clnt.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h
smp_clnt.o: /usr/px25/include/smp.h
