#
# LIB = library name
# SRC = list of source files the library is made of.
# LOCAL_CFLAGS = list of private Compiler flags
# WARNING : if library is a local one, comment the line after install:
# ( Do not install in project lib dir )
#

LIB =
SRC =
LOCAL_CFLAGS =

.SUFFIXES: .uil .uid .do

include	${PX25HOME}/doc/makefile.libstd
