#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = sm_mgr
SRC = sm_mgr.c smp_svc.c smp_xdr.c 
LOCAL_CFLAGS = -g -DDEBUG 
LOCAL_LIBES = -ldebug -lnsl
DIP_LIBS = ${PX25HOME}/lib/libdebug.a

include	${PX25HOME}/doc/makefile.std

protocol.h : protocol.x

# DO NOT DELETE THIS LINE -- make depend depends on it.

sm_mgr.o: /usr/include/stdio.h /usr/include/string.h /usr/include/signal.h
sm_mgr.o: /usr/include/sys/signal.h /usr/include/sys/types.h
sm_mgr.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_mgr.o: /usr/include/sys/time.h /usr/include/sys/tiuser.h
sm_mgr.o: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
sm_mgr.o: /usr/include/sys/stream.h /usr/include/sys/cred.h
sm_mgr.o: /usr/include/sys/vnode.h /usr/include/sys/mac.h
sm_mgr.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
sm_mgr.o: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
sm_mgr.o: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
sm_mgr.o: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
sm_mgr.o: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
sm_mgr.o: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
sm_mgr.o: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
sm_mgr.o: /usr/include/rpc/svc.h /usr/include/sys/select.h
sm_mgr.o: /usr/include/rpc/svc_auth.h /usr/include/ctype.h
sm_mgr.o: /usr/px25/include/px25_globals.h smp.h /usr/px25/include/debug.h
smp_svc.o: /usr/include/stdio.h /usr/include/signal.h
smp_svc.o: /usr/include/sys/signal.h /usr/include/sys/types.h
smp_svc.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_svc.o: /usr/include/sys/time.h /usr/include/sys/tiuser.h
smp_svc.o: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
smp_svc.o: /usr/include/sys/stream.h /usr/include/sys/cred.h
smp_svc.o: /usr/include/sys/vnode.h /usr/include/sys/mac.h
smp_svc.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
smp_svc.o: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
smp_svc.o: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
smp_svc.o: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
smp_svc.o: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
smp_svc.o: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
smp_svc.o: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
smp_svc.o: /usr/include/rpc/svc.h /usr/include/sys/select.h
smp_svc.o: /usr/include/rpc/svc_auth.h /usr/include/memory.h
smp_svc.o: /usr/include/stropts.h /usr/include/sys/stropts.h
smp_svc.o: /usr/include/sys/conf.h /usr/include/sys/secsys.h
smp_svc.o: /usr/include/netconfig.h /usr/include/sys/netconfig.h
smp_svc.o: /usr/include/sys/resource.h smp.h
smp_xdr.o: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_xdr.o: /usr/include/sys/types.h /usr/include/sys/time.h
smp_xdr.o: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
smp_xdr.o: /usr/include/netinet/in.h /usr/include/sys/stream.h
smp_xdr.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
smp_xdr.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
smp_xdr.o: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
smp_xdr.o: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
smp_xdr.o: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
smp_xdr.o: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
smp_xdr.o: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
smp_xdr.o: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
smp_xdr.o: /usr/include/rpc/token.h /usr/include/rpc/svc.h
smp_xdr.o: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h smp.h
# DEBUG Objects Dependencies

sm_mgr.do: /usr/include/stdio.h /usr/include/string.h /usr/include/signal.h
sm_mgr.do: /usr/include/sys/signal.h /usr/include/sys/types.h
sm_mgr.do: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
sm_mgr.do: /usr/include/sys/time.h /usr/include/sys/tiuser.h
sm_mgr.do: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
sm_mgr.do: /usr/include/sys/stream.h /usr/include/sys/cred.h
sm_mgr.do: /usr/include/sys/vnode.h /usr/include/sys/mac.h
sm_mgr.do: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
sm_mgr.do: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
sm_mgr.do: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
sm_mgr.do: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
sm_mgr.do: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
sm_mgr.do: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
sm_mgr.do: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
sm_mgr.do: /usr/include/rpc/svc.h /usr/include/sys/select.h
sm_mgr.do: /usr/include/rpc/svc_auth.h /usr/include/ctype.h
sm_mgr.do: /usr/px25/include/px25_globals.h smp.h /usr/px25/include/debug.h
smp_svc.do: /usr/include/stdio.h /usr/include/signal.h
smp_svc.do: /usr/include/sys/signal.h /usr/include/sys/types.h
smp_svc.do: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_svc.do: /usr/include/sys/time.h /usr/include/sys/tiuser.h
smp_svc.do: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
smp_svc.do: /usr/include/sys/stream.h /usr/include/sys/cred.h
smp_svc.do: /usr/include/sys/vnode.h /usr/include/sys/mac.h
smp_svc.do: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
smp_svc.do: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
smp_svc.do: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
smp_svc.do: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
smp_svc.do: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
smp_svc.do: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
smp_svc.do: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
smp_svc.do: /usr/include/rpc/svc.h /usr/include/sys/select.h
smp_svc.do: /usr/include/rpc/svc_auth.h /usr/include/memory.h
smp_svc.do: /usr/include/stropts.h /usr/include/sys/stropts.h
smp_svc.do: /usr/include/sys/conf.h /usr/include/sys/secsys.h
smp_svc.do: /usr/include/netconfig.h /usr/include/sys/netconfig.h
smp_svc.do: /usr/include/sys/resource.h smp.h
smp_xdr.do: /usr/include/rpc/rpc.h /usr/include/rpc/types.h
smp_xdr.do: /usr/include/sys/types.h /usr/include/sys/time.h
smp_xdr.do: /usr/include/sys/tiuser.h /usr/include/sys/fcntl.h
smp_xdr.do: /usr/include/netinet/in.h /usr/include/sys/stream.h
smp_xdr.do: /usr/include/sys/cred.h /usr/include/sys/vnode.h
smp_xdr.do: /usr/include/sys/mac.h /usr/include/sys/poll.h
smp_xdr.do: /usr/include/sys/strmdep.h /usr/include/sys/byteorder.h
smp_xdr.do: /usr/include/sys/socket.h /usr/include/sys/t_kuser.h
smp_xdr.do: /usr/include/rpc/xdr.h /usr/include/rpc/auth.h
smp_xdr.do: /usr/include/rpc/clnt.h /usr/include/rpc/rpc_com.h
smp_xdr.do: /usr/include/rpc/rpc_msg.h /usr/include/rpc/auth_sys.h
smp_xdr.do: /usr/include/rpc/auth_des.h /usr/include/rpc/auth_esv.h
smp_xdr.do: /usr/include/rpc/token.h /usr/include/rpc/svc.h
smp_xdr.do: /usr/include/sys/select.h /usr/include/rpc/svc_auth.h smp.h
