/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <rpc/rpc.h>
#include "smp.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
create_route_1(argp, clnt)
node *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, CREATE_ROUTE, xdr_node, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

node *
get_best_route_1(argp, clnt)
node *argp;
CLIENT *clnt;
{
    static node res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, GET_BEST_ROUTE, xdr_node, argp, xdr_node, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
free_route_1(argp, clnt)
node *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, FREE_ROUTE, xdr_node, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
incr_route_1(argp, clnt)
node *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, INCR_ROUTE, xdr_node, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
delete_route_1(argp, clnt)
node *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, DELETE_ROUTE, xdr_node, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
list_route_1(argp, clnt)
void *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, LIST_ROUTE, xdr_void, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
init_debug_1(argp, clnt)
int *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, INIT_DEBUG, xdr_int, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
end_debug_1(argp, clnt)
void *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, END_DEBUG, xdr_void, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
dump_1(argp, clnt)
char **argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, DUMP, xdr_wrapstring, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}

int *
load_1(argp, clnt)
void *argp;
CLIENT *clnt;
{
    static int res;

    (void) memset((char *)&res, 0, sizeof(res));
    if (clnt_call(clnt, LOAD, xdr_void, argp, xdr_int, &res, TIMEOUT) != RPC_SUCCESS)
    {
        return (NULL);
    }
    return (&res);
}
