#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = shell_x28
SRC = shell_x28.c
LOCAL_CFLAGS = -O
LOCAL_LIBES = -ldebug -lnsl -lsocket -lmos -llog
DIP_LIBS = ${PX25HOME}/lib/libmos.a ${PX25HOME}/lib/liblog.a

include	${PX25HOME}/doc/makefile.std
# DO NOT DELETE THIS LINE -- make depend depends on it.

shell_x28.o: /usr/include/stdio.h /usr/include/errno.h
shell_x28.o: /usr/include/sys/errno.h /usr/include/sys/fcntl.h
shell_x28.o: /usr/include/sys/types.h /usr/include/signal.h
shell_x28.o: /usr/include/sys/signal.h /usr/include/sys/time.h
shell_x28.o: /usr/include/termio.h /usr/include/sys/termio.h
shell_x28.o: /usr/include/sys/termios.h /usr/include/sys/stream.h
shell_x28.o: /usr/include/sys/cred.h /usr/include/sys/vnode.h
shell_x28.o: /usr/include/sys/mac.h /usr/include/sys/poll.h
shell_x28.o: /usr/include/sys/strmdep.h /usr/include/sys/stropts.h
shell_x28.o: /usr/include/sys/conf.h /usr/include/sys/secsys.h
shell_x28.o: /usr/px25/include/px25_globals.h /usr/px25/include/errlog.h
shell_x28.o: /usr/px25/include/debug.h
# DEBUG Objects Dependencies

shell_x28.do: /usr/include/stdio.h /usr/include/errno.h
shell_x28.do: /usr/include/sys/errno.h /usr/include/sys/fcntl.h
shell_x28.do: /usr/include/sys/types.h /usr/include/signal.h
shell_x28.do: /usr/include/sys/signal.h /usr/include/sys/time.h
shell_x28.do: /usr/include/termio.h /usr/include/sys/termio.h
shell_x28.do: /usr/include/sys/termios.h /usr/include/sys/stream.h
shell_x28.do: /usr/include/sys/cred.h /usr/include/sys/vnode.h
shell_x28.do: /usr/include/sys/mac.h /usr/include/sys/poll.h
shell_x28.do: /usr/include/sys/strmdep.h /usr/include/sys/stropts.h
shell_x28.do: /usr/include/sys/conf.h /usr/include/sys/secsys.h
shell_x28.do: /usr/px25/include/px25_globals.h /usr/px25/include/errlog.h
shell_x28.do: /usr/px25/include/debug.h
