#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = sm_test
SRC = sm_test.c
LOCAL_CFLAGS = -g
LOCAL_LIBES = -lsmreq -ldebug -lnsl
DIP_LIBS = ${PX25HOME}/lib/libsmreq.a ${PX25HOME}/lib/libdebug.a

include	${PX25HOME}/doc/makefile.std
# DO NOT DELETE THIS LINE -- make depend depends on it.

sm_test.o: /usr/include/stdio.h /usr/include/rpc/rpc.h
sm_test.o: /usr/include/rpc/types.h /usr/include/sys/types.h
sm_test.o: /usr/include/sys/time.h /usr/include/sys/tiuser.h
sm_test.o: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
sm_test.o: /usr/include/sys/stream.h /usr/include/sys/cred.h
sm_test.o: /usr/include/sys/vnode.h /usr/include/sys/mac.h
sm_test.o: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
sm_test.o: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
sm_test.o: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
sm_test.o: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
sm_test.o: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
sm_test.o: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
sm_test.o: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
sm_test.o: /usr/include/rpc/svc.h /usr/include/sys/select.h
sm_test.o: /usr/include/rpc/svc_auth.h /usr/px25/include/px25_globals.h
sm_test.o: /usr/px25/include/debug.h /usr/px25/include/sm.h
sm_test.o: /usr/px25/include/group.h
# DEBUG Objects Dependencies

sm_test.do: /usr/include/stdio.h /usr/include/rpc/rpc.h
sm_test.do: /usr/include/rpc/types.h /usr/include/sys/types.h
sm_test.do: /usr/include/sys/time.h /usr/include/sys/tiuser.h
sm_test.do: /usr/include/sys/fcntl.h /usr/include/netinet/in.h
sm_test.do: /usr/include/sys/stream.h /usr/include/sys/cred.h
sm_test.do: /usr/include/sys/vnode.h /usr/include/sys/mac.h
sm_test.do: /usr/include/sys/poll.h /usr/include/sys/strmdep.h
sm_test.do: /usr/include/sys/byteorder.h /usr/include/sys/socket.h
sm_test.do: /usr/include/sys/t_kuser.h /usr/include/rpc/xdr.h
sm_test.do: /usr/include/rpc/auth.h /usr/include/rpc/clnt.h
sm_test.do: /usr/include/rpc/rpc_com.h /usr/include/rpc/rpc_msg.h
sm_test.do: /usr/include/rpc/auth_sys.h /usr/include/rpc/auth_des.h
sm_test.do: /usr/include/rpc/auth_esv.h /usr/include/rpc/token.h
sm_test.do: /usr/include/rpc/svc.h /usr/include/sys/select.h
sm_test.do: /usr/include/rpc/svc_auth.h /usr/px25/include/px25_globals.h
sm_test.do: /usr/px25/include/debug.h /usr/px25/include/sm.h
sm_test.do: /usr/px25/include/group.h
