#
# Template makefile for PX25
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE = pos
SRC = pos.c signal.c
LOCAL_CFLAGS = -I/usr/include/eicon -g
LOCAL_LIBES = -lx25 -lEec
DIP_LIBS = 

include	${PX25HOME}/doc/makefile.std
